### ISSUE TITLE
Add contributing.md file

### ISSUE THREAD

**Issue by nveenjain** [nveenjain/gravity#2]
Currently, the project doesn't have a contributing.md file.

Create a contributin.md file, with the process on how to contribute to the project.

Major steps which needs to be included:-

1. Fork the repo
2. Clone the repo
3. Fix the bug
4. Send a PR

Also, it would be great if you could give a link to [this awesome course by @kentcdodds](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github).

If you're stuck somewhere, feel free to ask.

**Comment by WOLFI3654** [comment]
I can do that

**Comment by nveenjain** [comment]
sure @WOLFI3654, go ahead!
